version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - lumet_net
    depends_on:
      - db
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: lumen_app
    working_dir: /var/www/html/public
    command: php-fpm
    volumes: 
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - lumet_net
    depends_on:
      - db

  db:
    image: mysql:5.7.34
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - .dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: belajarbareng_db
      MYSQL_USER: belajarbareng_dbadmin
      MYSQL_PASSWORD: rahasia
      MYSQL_ROOT_PASSWORD: rahasia
    networks:
      - lumet_net

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks: 
      - lumet_net

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes: 
      - .:/var/www/html
    depends_on: 
      - db
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks: 
      - lumet_net

networks:
  lumet_net:
